   version: "3.9"
   services:
     mysql:
       image: mysql:8.0
       container_name: mysql_mercadopago
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: mercadopago
       ports:
         - "3306:3306"
       volumes:
         - db_data:/var/lib/mysql
   volumes:
     db_data: